services:
  backend:
    image: ebook-backend
    container_name: ebook-backend
    ports:
      - 8080:8080
    networks:
      - my-network
    volumes:
      - ../backend:/backend
      - E:/.m2/repository:/root/.m2/repository
    env_file:
      - ../deployment/backend/.env
  frontend:
    image: ebook-frontend
    container_name: ebook-frontend
    ports:
      - 5173:5173
    networks:
      - my-network
    volumes:
      - ../frontend:/frontend
    # command: sh -c "npm install && npm start -- --host"
  # mysql:
  #   image: ebook-mysql
  #   container_name: ebook-mysql
  #   ports:
  #     - 3306:3306
  #   networks:
  #     - my-network
  #   volumes:
  #     - E:/MySQL/ebook:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456
  kafka:
    image: apache/kafka:3.7.0
    container_name: ebook-kafka
    ports:
      - 9092:9092
    networks:
      - my-network

networks:
  my-network:
    name: my-network
    driver: bridge
