server:
  port: 8000

spring:
  application:
    name: gateway
  cloud: # 服务注册
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR}
    gateway:
      routes:
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/search/**

        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/**

