services:
  my-nginx:
    image: ebook-nginx
    container_name: ebook-nginx
    ports:
      - 80:80
    networks:
      - my-network
    restart: always
  backend:
    image: ebook-backend
    container_name: ebook-backend
    ports:
      - 8080:8080
    networks:
      - my-network
    env_file:
      - backend.env
  frontend:
    image: ebook-frontend
    container_name: ebook-frontend
    ports:
      - 3000:3000
    networks:
      - my-network
      
networks:
  my-network:
    name: my-network
    driver: bridge
