services:
  my-nginx:
    image: ebook-nginx
    container_name: ebook-nginx
    ports:
      - 80:80
    networks:
      - my-network
    restart: always
  backend:
    image: ebook-backend
    container_name: ebook-backend
    ports:
      - 8080:8080
    networks:
      - my-network
    env_file:
      - backend/.env
    restart: always
  frontend:
    image: ebook-frontend
    container_name: ebook-frontend
    ports:
      - 3000:3000
    networks:
      - my-network
    restart: always
  kafka:
    image: apache/kafka:3.7.0
    container_name: ebook-kafka
    ports:
      - 9092:9092
    networks:
      - my-network
    environment:
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://ebook-kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
      - KAFKA_NUM_NETWORK_THREADS=3
      - KAFKA_NUM_IO_THREADS=8
      - KAFKA_SOCKET_SEND_BUFFER_BYTES=102400
      - KAFKA_SOCKET_RECEIVE_BUFFER_BYTES=102400
      - KAFKA_SOCKET_REQUEST_MAX_BYTES=104857600
      - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs
      - KAFKA_NUM_PARTITIONS=1
      - KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_LOG_RETENTION_HOURS=168
      - KAFKA_LOG_SEGMENT_BYTES=1073741824
      - KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS=300000
    restart: always
networks:
  my-network:
    name: my-network
    driver: bridge
