server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebookstore
    username: root
    password: zhuhan1118
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: user
      password: 123
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false