server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebookstore
    username: root
    password: zhuhan1118
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if- no-handler-found: true
  web:
    resources:
      add-mappings: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update