server:
  port: ${BACKEND_PORT}
  servlet:
    session:
      timeout: 30d # 30 days

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if- no-handler-found: true
    path match:
      matching-strategy: ant_path_matcher
  web:
    resources:
      static-locations: classpath:/static/
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# S3配置
s3:
  bucket_name: ${S3_BUCKET_NAME}
  access_key: ${S3_ACCESS_KEY}
  secret_key: ${S3_SECRET_KEY}
  endpoint: ${S3_ENDPOINT}
  region: ${S3_REGION}
  domain: ${S3_DOMAIN}