name: Deploy Backend

on:
  push:
    branches:
      - main # 你可以根据需要修改触发分支
    paths:
      - "backend/**"
      - "deployment/backend/**"

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 配置 JDK 17 环境
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven # 使用 Maven 缓存本地仓库的依赖
          cache-dependency-path: backend/pom.xml

      - name: Build project
        run: mvn clean package
        working-directory: backend

      - name: Upload files
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "deployment/backend/Dockerfile,backend/target/backend-0.0.1-SNAPSHOT.jar"
          target: "/root/ebookstore/backend"
          strip_components: 2 # 去掉前两级目录

      - name: Execute script
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /root/ebookstore/backend
            sudo docker build -t ebook-backend .
            cd /root/ebookstore
            docker-compose down 
            docker-compose up -d
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          pass: ${{ secrets.SSH_PASSWORD}}
