name: Update Docker Compose

on:
  push:
    branches:
      - main # 你可以根据需要修改触发分支
    paths:
      - "deployment/docker-compose.yml"

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload files
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "deployment/docker-compose.yml"
          target: "/root/ebookstore"
          strip_components: 1 

      - name: Execute script
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /root/ebookstore
            docker-compose down 
            docker-compose up -d
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          pass: ${{ secrets.SSH_PASSWORD}}
