name: Deploy Frontend

on:
  push:
    branches:
      - github-actions-test  # 你可以根据需要修改触发分支
    paths:
      - 'frontend/**'  # 仅当 frontend 文件夹下有更改时触发
  workflow_dispatch: # 手动触发工作流程

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build project
        run: npm run build
        working-directory: frontend

      - name: Upload files via SSH
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "frontend/dist/,deployment/frontend/server.js,deployment/frontend/Dockerfile"
          target: "/root/ebookstore/frontend"

      - name: Build Docker image
        run: docker build -t ebook-frontend .
        working-directory: /root/ebookstore/frontend

      - name: Shutdown Docker containers
        run: docker-compose down
        working-directory: /root/ebookstore

      - name: Start Docker containers
        run: docker-compose up -d
        working-directory: /root/ebookstore
